# Site setings
name: 'Ashley Van Spankeren'
author:
  image: 'authorimage_back.jpg'
  greetings: "Curious explorer, innate problem solver."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://ashvan.ca/


# Contact form setings
email: ashleyvansp@gmail.com
contact_page_description: Whether it's an inquiry, comment, or just wanting to grab a cup of coffee, I look forward to hearing from you via <a href="https://www.linkedin.com/in/ashleyvansp">LinkedIn</a> or <a href="mailto:ashleyvansp@gmail.com">email</a>.

# Social links
github: 'ashleyvansp'
linkedin: 'ashleyvansp'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Curriculum Vitae
    url: /curriculum-vitae
  - text: Contact
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
